spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # DATABASE CONFIG
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/minacloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
    initialization-mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  maxHttpHeaderSize: 50000000
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 100
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: debug
#            namedparam:
#              NamedParameterJdbcTemplate: debug

minacloud:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket-name: test
    allow-file-type: jpg,png,jpeg,zip,rar,doc,docx,xls,xlsx,img,iso
    # 分片上传有效期: 秒
    chunk-upload-expiry-second: 86400